### ISSUE TITLE
Add more user friendly error reporting when get.indicators fails

### ISSUE THREAD

**Issue by johnsonryan** [elsen-trading/elsen-python#2]
Currently, we're getting the following error when running the following in iPython Notebook:
```
rsi = elsen.get_indicators('rsi')
print rsi.description
```
Returns:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-22-1208a4279442> in <module>()
      1 rsi = elsen.get_indicators('rsi')
----> 2 print rsi.description

AttributeError: 'list' object has no attribute 'description'
```

As a user, I have no idea what this error means. It would be preferable to see a more descriptive message such as "Cannot find indicator in database".

**Comment by sdiehl** [comment]
Documentation was out sync, should be rsi.short_desc.

```python
In [0]: rsi = elsen.get_indicators('rsi')
In [1]: print rsi.description
The Relative Strength Index (RSI) measures the trend of a securities price by measuring the ratio of average gains to average losses, and converting it to an index from 1 to 100.
```

As far the more general problem, if the user tries to access field on an object that doesn't have those fields there's nothing we can do to save them from themselves, that's just how Python is set up. More experienced users wouldn't run into this problem since you tab complete an object it gives the available accessor.

```python
In [0]: Example.rsi.<Tab>
Example.rsi.description   Example.rsi.inputs        Example.rsi.short_desc    
Example.rsi.display_name  Example.rsi.name   
```

**Comment by sdiehl** [comment]
Actually I can't even find documentation that describes "rsi.description" anywhere, so must have been a very old notebook or something. Pull the latest elsen-demos from Git and ``pip install elsen`` to get the latest code.
