### ISSUE TITLE
Python Demo crossover indicator

### ISSUE THREAD

**Issue by nadimzameli** [elsen-trading/elsen-python#4]
@justinwhite 
Input: ind = Indicator(action=BUY, name=cross, line1={ lookback=15, name=SMA }, line2={ lookback=30, name=SMA })

Output:  File "<ipython-input-15-810371d9bf97>", line 1
    ind = Indicator(action=BUY, name=cross, line1={ lookback=15, name=SMA }, line2={ lookback=30, name=SMA })
                                                            ^
SyntaxError: invalid syntax

**Comment by nadimzameli** [comment]
ind = Indicator(action=BUY, name=cross, line1={ 'lookback':15, 'name':SMA }, line2={ 'lookback':30, 'name':SMA })

This worked

**Comment by sdiehl** [comment]
So is the issue just one of Python syntax?

**Comment by zsheffer** [comment]
I think the issue is because the keys are not strings.

**Comment by sdiehl** [comment]
Yeah, I think it's just a misunderstanding about Python dicts:

https://docs.python.org/2/library/stdtypes.html#mapping-types-dict
